config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :comments, except: [:edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :name, presence: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5, maximum: 150 }
  validates :content, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :warning, :success, :info
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:success] = 'Comment was successfully created'
      redirect_to post_path(@post)
    else
      flash.now[:warning] = 'Comment failed to create'
      render "posts/show"
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    flash[:success] = 'Comment deleted'
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :content).merge(post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:success] = 'Post was successfully created'
      redirect_to @post
    else
      flash.now[:warning] = 'Post creation failed'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = 'Post was successfully updated'
      redirect_to @post
    else
      flash.now[:warning] = 'Post edit failed'
      render 'edit'
    end
  end

  def show
    @comment = Comment.new(post_id: @post.id)
  end

  def destroy
    if @post.destroy
      flash[:success] = 'Post was successfully deleted.'
      redirect_to root_path
    else
      flash[:warning] = 'Post delete failed'
      redirect_to @post
    end
  end
  

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when "warning" then "notification is-warning"
        when "success" then "notification is-success"
        when "info" then "notification is-info"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="media">
  <div class="media-content">
    <strong><%= comment.name%></strong>
    <p><%= comment.content%></p>
  </div>
  <div class="media-right">
    <%= link_to '', post_comment_path(comment.post, comment),
                          method: :delete, 
                          data: { confirm: "Are you sure you would like to delete this comment?" },
                          class: "delete" %>
  </div>
</div> 

app/views/comments/_form.html.erb
<%= form_with model: [post, comment], local: true do |f| %>
  <div class="field">
    <%= render 'shared/error_messages', object: comment %>
  </div>

  <div class="field">
    <%= f.label :name, class: "label" %>
    <div class="control">
      <%= f.text_field :name, class:"input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :content,"Leave a comment", class: "label" %>
    <div class="control">
      <%= f.text_area :content, class: "textarea", rows:5, placeholder: "Your comment..." %>
    </div>
  </div>
  
  <div class="control buttons">
    <%= f.submit "Comment", class: "button is-dark" %>
    <%= f.submit "Cancel", type: :reset, class: "button" %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <section class="hero is-small is-dark is-bold">
      <div class="hero-body">
        <nav class="navbar" role="navigation" aria-label="main navigation">
          <div class="navbar-brand">
            <%= link_to root_path do %>
              <%= image_tag 'logo-white.png', size: "200x200" , class: "logo" %>
            <% end %>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>

          <div id="navbar" class="navbar-menu">
            <div class="navbar-start">
            </div>

            <div class="navbar-end">
              <div class="navbar-item">
                <div class="buttons">
                  <a class="button is-dark">
                    <strong>Sign up</strong>
                  </a>
                  <a class="button is-light">
                    Log in
                  </a>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </section>

    <!-- # flash messages --> 
    <section>
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value %>
        </div>
      <% end %>
    </section>

    <section class="section">
      <div class="columns">
        <div class="column is-narrow">
          <div class="menu">
            <div class="menu-list">
              <%= link_to "Create New Post", new_post_path, class:"button is-dark mb-2" %>
              <%= link_to "Posts", posts_path, class:"button is-dark" %>
            </div>
          </div>
        </div>
        <div class="column">
          <%= yield %>
        </div>
        <!-- Put yield in a column -->

      </div>
    </section>

  <script>
    document.addEventListener('DOMContentLoaded', () => {

    // Get all "navbar-burger" elements
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {

      // Add a click event on each of them
      $navbarBurgers.forEach( el => {
        el.addEventListener('click', () => {

          // Get the target from the "data-target" attribute
          const target = el.dataset.target;
          const $target = document.getElementById(target);

          // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');

        });
      });
    }

  });
  </script>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <h1 class="title"><%= yield :page_title %></h1>
  <%= form_with model: post, local: true do |f|%>
    <div class="field">
      <%= render 'shared/error_messages', object: post %>
    </div>

    <div class="field">
      <%= f.label :title, class: "label" %>
      <div class="control">
        <%= f.text_field :title, class:"input" %>
      </div>
    </div>

    <div class="field">
      <%= f.label :content, class: "label" %>
      <div class="control">
        <%= f.text_area :content, class: "textarea", rows:10 %>
      </div>
    </div>

    <div class="control buttons">
      <%= f.submit class: "button is-dark" %>
      <%= link_to 'Cancel', root_path, class: "button" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :page_title, "Edit Post" %>


<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class="container">
  <h1 class="title">Posts</h1>
  <% @posts.each do |post| %>
  <div class="card has-background-dark  has-text-white mb-5">
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p class="title is-4"><%= link_to post.title, post, class: "has-text-white" %></p>
          <p><%= truncate(post.content, length: 50, separator: ' ') {link_to " Read More", post, class: "has-text-white has-text-weight-semibold"} %></p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<% content_for :page_title, "New Post" %>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="container">
  <div class="columns is-desktop">
    <div class="column mr-3">
    
      <div class="post">
        <div class="level ">
          <div class="level-left">
            <h1 class="title"><%= @post.title%></h1>
          </div>
          <div class="level-right">
            <p>Date: <%= (@post.updated_at).strftime("%d %b %Y") %></p>
          </div>
        </div>
        <%= simple_format(@post.content, class: "mb-5") %>
      </div>

      <div class="comment-form mt-5">
        <%= render 'comments/form', post: @post, comment: @comment %>
      </div>

      <div class="comments">
        <h1 class="subtitle is-5"><%= pluralize( @post.comments.count,"comment") %></h1>
        <%= render @post.comments %>
      </div>
    </div>

    <div class="column is-one-fifth post-actions">
      <div class="menu mt-2">
        <div class="menu-label">
          Actions
        </div>
        <div class="menu-list">
          <%= link_to 'Edit', edit_post_path(@post), class: "button is-dark is-outlined" %>
          <%= link_to 'Delete', post_path(@post), method: :delete,
                                                  data: { confirm: "Are you sure you would like to delete this post?" },
                                                  class: "button is-danger is-outlined" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="notification is-danger is-light">
    <label class="label"><%= pluralize(object.errors.count, "error") %> prevented this post from being saved:</label>
    <ul>
    <% object.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  </div>
<% end %>